// Build script para injetar variáveis de ambiente no config.js
// Executado pelo Netlify durante o deploy

const fs = require('fs');

const config = {
    SUPABASE_URL: process.env.SUPABASE_URL || '',
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || ''
};

const content = `// Auto-generated by build.js - DO NOT EDIT
// Configure as variáveis de ambiente no Netlify
const CONFIG = ${JSON.stringify(config, null, 4)};
`;

fs.writeFileSync('config.js', content);

console.log('✅ config.js gerado com sucesso!');
console.log(`   SUPABASE_URL: ${config.SUPABASE_URL ? '✓ configurado' : '⚠ não configurado'}`);
console.log(`   SUPABASE_ANON_KEY: ${config.SUPABASE_ANON_KEY ? '✓ configurado' : '⚠ não configurado'}`);
